import type { Metadata } from "next";
import { Poppins, DM_Sans, Geist } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import WalletProvider from "../context/WalletProvider";
import { Toaster } from "react-hot-toast";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${poppins.variable} ${dmSans.variable}`}
      >
        <div>
          <Toaster position="top-center" reverseOrder={false} />
        </div>
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
